### ISSUE TITLE
Add territory dropdown in dashboard view

### ISSUE THREAD

**Issue by PierrickLozach** [PierrickI3/CCCRequestsForm#21]

**Comment by PierrickLozach** [comment]
I had to partially work on this (Shahzad wanted to show this to Execs this afternoon). I have added a new chart for territory and a dropdown but I am not sure how to filter all other charts based on the subRegion

**Comment by szlaskidaniel** [comment]
Working on this

**Comment by szlaskidaniel** [comment]
Done. Remove not required code. All charts now honor subRegion selection.
If you check the code, we don't need IF THEN for new fields, it's quite well designed :)
