### ISSUE TITLE
Create a maintenance page + alert to top of all pages to warn about upcoming maintenance schedule

### ISSUE THREAD

**Issue by PierrickLozach** [PierrickI3/CCCRequestsForm#26]

**Comment by szlaskidaniel** [comment]
That's a good one. Top banner on all pages with info that "New version ahead, possible issues with tool" , once we publish all changes, after 1 day, we can push new update where we just remove that header. 
Or even better -> create new Lambda function which will say "maintenance mode ON/OFF" - the code will adapt. Value for Lambda will be read from table / env. variable
