### ISSUE TITLE
Add keyword to prevent tests to generate emails and notifications

### ISSUE THREAD

**Issue by PierrickLozach** [PierrickI3/CCCRequestsForm#34]
Something like: if description contains "TestECCC", then it should not send an email or push a notification to GC chat room.

This will be used for testing purposes

**Comment by szlaskidaniel** [comment]
It should generate emails to us only and send notifications to our ECCC Senior Cloud Technical Architect group?

**Comment by PierrickLozach** [comment]
Craig and Rohit are also in that group but that could work
